Fix checks issues
PaloAltoNetworks/terraform-google-vmseries-modules pull request #166
Opened 2023-03-22 10:26 UTC by mariuszgebala

## Description

Update minimum Terraform version to 1.0.0 and google provider to 4.x

## Motivation and Context

https://github.com/PaloAltoNetworks/terraform-google-vmseries-modules/issues/156
https://github.com/PaloAltoNetworks/terraform-google-vmseries-modules/issues/147

## How Has This Been Tested?

Deployed every module and test if it works properly

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes if appropriate.
- [x] All new and existing tests passed.

2023-03-28 10:53 UTC, michalbil requested changes

2023-03-28 10:53 UTC, michalbil commented on .github/workflows/ci.yml
> +          terraform_version: 1.0.0 # Bumped from 0.15.3 (28/03/2023s)
```suggestion
          terraform_version: 1.0.0
```

2023-03-28 10:53 UTC, michalbil commented on modules/iam_service_account/main.tf
>    role     = each.value
```suggestion
resource "google_project_iam_member" "this" {
  for_each = var.roles
  
  project  = var.project_id
  role     = each.value
```

2023-06-01 13:59 UTC, michalbil approved these changes

2023-06-01 14:02 UTC, horiagunica approved these changes
LGTM! 👍

2023-06-01 16:19 UTC, merged