refactor: 171 panorama example refactor
PaloAltoNetworks/terraform-google-vmseries-modules pull request #173
Opened 2023-04-04 13:19 UTC by horiagunica

## Description

- Panorama examples refactor
- This PR closes #171 

## Motivation and Context

- Panorama example flexibility and documentation

## How Has This Been Tested?

## Screenshots (if appropriate)

## Types of changes

- Refactor

## Checklist

- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes if appropriate.
- [x] All new and existing tests passed.

2023-04-04 16:00 UTC, michalbil requested changes

2023-04-04 16:00 UTC, michalbil commented on .github/workflows/ci.yml
> +          terraform_version: 1.0.0 # Bumped from 0.15.3 (28/03/2023s)
```suggestion
          terraform_version: 1.0.0
```

2023-04-04 16:00 UTC, michalbil commented on examples/panorama/README.md
> +The scope of this code is to successfuly deploy one or more panorama instances in a single project and region in Google Cloud.
```suggestion
The scope of this code is to deploy one or more Panorama instances in a single project and region in Google Cloud.
```

2023-04-04 16:00 UTC, michalbil commented on examples/panorama/README.md
> + - The code builds a single region topology for Panorama
This is already stated in the line above.

2023-04-04 16:00 UTC, michalbil commented on examples/panorama/variables.tf
> +    Available options :
For this kind of details let's maybe add a link directly to module input description?

2023-04-04 16:47 UTC, migara commented
@horiagunica let's add the topology image directly onto the README. Just copy and paste the image onto your markdown

2023-04-04 17:04 UTC, horiagunica commented on examples/panorama/main.tf
>    zone              = data.google_compute_zones.this.names[0]
Added the zone as input in tfvars.

2023-04-04 17:05 UTC, horiagunica commented on examples/panorama/main.tf
> +  depends_on        = [module.vpc]
Reffered VPC module

2023-04-17 11:54 UTC, horiagunica commented on examples/panorama/README.md
> +2. Configure the terraform [google provider](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/getting_started#configuring-the-provider)
You are right, applied!

2023-04-17 11:54 UTC, horiagunica commented on examples/panorama/variables.tf
> +  default     = "example-"
Defaulted to empty string.

2023-04-21 12:49 UTC, migara approved these changes
Great work!

2023-04-26 07:47 UTC, michalbil approved these changes

2023-04-26 07:47 UTC, michalbil commented on examples/panorama/outputs.tf
>  output "panorama_private_ip" {
```suggestion
output "panorama_private_ips" {
```

2023-04-26 07:47 UTC, michalbil commented on examples/panorama/outputs.tf
>  output "panorama_public_ip" {
```suggestion
output "panorama_public_ips" {
```

2023-04-26 07:47 UTC, michalbil commented on examples/panorama/variables.tf
> +        subnet_name       = "example-panorama-subnet"
```suggestion
        subnet_name       = "panorama-subnet"
```

2023-04-26 07:47 UTC, michalbil commented on examples/panorama/variables.tf
> +        panorama_subnet   = "example-panorama-subnet"
```suggestion
        panorama_subnet   = "panorama-subnet"
```

2023-05-17 15:43 UTC, merged