Changes:
PaloAltoNetworks/terraform-google-vmseries-modules pull request #181
Opened 2023-04-14 15:35 UTC by ntwrkguru

Updated bootstrap module to allow for the input of a structured bootstrap package

Updated module to allow any number of files with any names to be added to the bucket for bootstrapping. Left the existing functionality intact to allow the legacy `files` object to be passed.

## Motivation and Context

Fixes #180 

## How Has This Been Tested?

Local terraform plan/apply/destroy

## Screenshots (if appropriate)

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [ x ] I have updated the documentation accordingly.
- [ x ] I have read the **CONTRIBUTING** document.
- [ x ] I have added tests to cover my changes if appropriate.
- [ x ] All new and existing tests passed.

2023-04-14 19:02 UTC, michalbil commented
cc @horiagunica

2023-04-19 10:24 UTC, migara requested changes

2023-04-19 10:24 UTC, migara commented on modules/bootstrap/variables.tf
> +variable "bootstrap_files" {
```suggestion
variable "bootstrap_files_dir" {
```

2023-04-19 10:24 UTC, migara commented on modules/bootstrap/variables.tf
> +  description = "Location to the bootstrap file structure. More infor can be found under https://docs.paloaltonetworks.com/vm-series/9-1/vm-series-deployment/bootstrap-the-vm-series-firewall/bootstra
```suggestion
  description = "Bootstrap file directory. More information can be found at https://docs.paloaltonetworks.com/vm-series/9-1/vm-series-deployment/bootstrap-the-vm-series-firewall/bootstrap-package"
```

2023-04-19 10:24 UTC, migara commented on modules/bootstrap/variables.tf
> +  default     = "./bootstrap_files"
```suggestion
```

2023-04-19 10:24 UTC, migara commented on modules/bootstrap/variables.tf
> +  default     = "./bootstrap_files"
It make sense to have this explicitly specified by the user to avoid any ambiguous outcomes

2023-04-19 10:24 UTC, migara commented on modules/bootstrap/main.tf
> +  filenames           = merge(local.bootstrap_filenames, var.files)
We should create a merge function to compare values of these two maps (local.bootstrap_filenames, var.files), instead of their keys.

2023-04-21 12:39 UTC, migara approved these changes
LGTM 👍🏽

2023-06-12 18:44 UTC, merged